### ISSUE TITLE
Can we add versioning to this?

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot-cpp-template#60]
I was using latest main and yesterday a breaking change was added and now my builds fail: https://github.com/libriscv/godot-sandbox/actions/runs/11711734886/job/32620906679

Can we version this repo somehow? Eg. starting from now lets say the branch instead of main there is 1.0, and version keep coming, and every breaking change adds a version.

**Comment by Ivorforce** [comment]
Hi, I just commented about the failing build in #61.

Regarding versioning, I agree that's probably a good idea! 

For the moment, I'd advise you to depend on a specific git hash or tag though instead of a branch for runners. The recent contribution that broke your build was a bug fix, so it may not even have gotten a major version increase even with versioning.

**Comment by Ughuuu** [comment]
Fair enough. Thanks for responding. Updated the path and now builds work. Thanks for fixing, ill check the cache also.

**Comment by dsnopek** [comment]
Should the GitHub Action be moved to its own repo perhaps?

This repo is a template, which is only meant to be copied when a project is first created - we should be able to change almost anything we want without affecting backwards compatibility.

**Comment by paddy-exe** [comment]
I concur with David. As a template the main goal is to provide a functioning project to get started. If you want to have a separate repo with the actions used here so you can pull the updates into your repo that would be a different discussion to have.
